### ISSUE TITLE
Please tell me what the problem is?

### ISSUE THREAD

**Issue by EricDaJiang** [offroad-robotics/otter_ros#2]
ros2 launch otter_ros otter_base_launch.py
[INFO] [launch]: All log files can be found below /home/leojt/.ros/log/2024-08-15-11-11-35-248676-Y7000P-135727
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [otter_publisher-1]: process started with pid [135728]
[INFO] [otter_subscriber-2]: process started with pid [135730]
[INFO] [otter_tf2_broadcaster-3]: process started with pid [135732]
[INFO] [static_transform_publisher-4]: process started with pid [135734]
[INFO] [static_transform_publisher-5]: process started with pid [135736]
[INFO] [static_transform_publisher-6]: process started with pid [135738]
[INFO] [ros2-7]: process started with pid [135740]
[static_transform_publisher-4] [WARN] [1723691495.376267241] []: Old-style arguments are deprecated; see --help for new-style arguments
[static_transform_publisher-5] [WARN] [1723691495.376743798] []: Old-style arguments are deprecated; see --help for new-style arguments
[static_transform_publisher-6] [WARN] [1723691495.377529273] []: Old-style arguments are deprecated; see --help for new-style arguments
[static_transform_publisher-4] [INFO] [1723691495.385315605] [static_transform_publisher_e4JUi3TFlNM9iBsn]: Spinning until stopped - publishing transform
[static_transform_publisher-4] translation: ('0.000000', '0.000000', '0.000000')
[static_transform_publisher-4] rotation: ('0.707107', '0.707107', '-0.000000', '-0.000000')
[static_transform_publisher-4] from 'world' to 'world_ned'
[static_transform_publisher-6] [INFO] [1723691495.385386961] [static_transform_publisher_RNthXfFDRBWdjkFT]: Spinning until stopped - publishing transform
[static_transform_publisher-6] translation: ('-0.400000', '0.000000', '-0.500000')
[static_transform_publisher-6] rotation: ('1.000000', '0.000000', '-0.000000', '-0.000000')
[static_transform_publisher-6] from 'otter' to 'velodyne'
[static_transform_publisher-5] [INFO] [1723691495.389684401] [static_transform_publisher_39zU6LM8HohSyvBf]: Spinning until stopped - publishing transform
[static_transform_publisher-5] translation: ('0.000000', '0.000000', '0.000000')
[static_transform_publisher-5] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
[static_transform_publisher-5] from 'otter' to 'ins'
[ros2-7] usage: ros2 bag record [-h] [-a] [-e REGEX] [-x EXCLUDE]
[ros2-7]                        [--include-unpublished-topics]
[ros2-7]                        [--include-hidden-topics] [-o OUTPUT]
[ros2-7]                        [-s {sqlite3,my_test_plugin}] [-f {s,a}]
[ros2-7]                        [--no-discovery] [-p POLLING_INTERVAL]
[ros2-7]                        [-b MAX_BAG_SIZE] [-d MAX_BAG_DURATION]
[ros2-7]                        [--max-cache-size MAX_CACHE_SIZE]
[ros2-7]                        [--compression-mode {none,file,message}]
[ros2-7]                        [--compression-format {zstd,fake_comp}]
[ros2-7]                        [--compression-queue-size COMPRESSION_QUEUE_SIZE]
[ros2-7]                        [--compression-threads COMPRESSION_THREADS]
[ros2-7]                        [--snapshot-mode] [--ignore-leaf-topics]
[ros2-7]                        [--qos-profile-overrides-path QOS_PROFILE_OVERRIDES_PATH]
[ros2-7]                        [--storage-preset-profile STORAGE_PRESET_PROFILE]
[ros2-7]                        [--storage-config-file STORAGE_CONFIG_FILE]
[ros2-7]                        [--start-paused] [--use-sim-time]
[ros2-7]                        [--log-level {debug,info,warn,error,fatal}]
[ros2-7]                        [topics ...]
[ros2-7] ros2 bag record: error: argument -s/--storage: invalid choice: 'mcap' (choose from 'sqlite3', 'my_test_plugin')
[ERROR] [ros2-7]: process has died [pid 135740, exit code 2, cmd 'ros2 bag record -a -o otter_bag_2024_08_15T11_11_35 --storage mcap'].
^C[WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
[static_transform_publisher-4] [INFO] [1723691500.312881837] [rclcpp]: signal_handler(signum=2)
[otter_publisher-1] Traceback (most recent call last):
[otter_publisher-1]   File "/home/leojt/otter_ws/install/otter_ros/lib/otter_ros/otter_publisher", line 33, in <module>
[otter_publisher-1]     sys.exit(load_entry_point('otter-ros==1.0.0', 'console_scripts', 'otter_publisher')())
[otter_publisher-1]   File "/home/leojt/otter_ws/build/otter_ros/otter_ros/otter_publisher.py", line 176, in main
[static_transform_publisher-6] [INFO] [1723691500.313003607] [rclcpp]: signal_handler(signum=2)
[static_transform_publisher-5] [INFO] [1723691500.313003374] [rclcpp]: signal_handler(signum=2)
[otter_subscriber-2] Traceback (most recent call last):
[otter_subscriber-2]   File "/home/leojt/otter_ws/install/otter_ros/lib/otter_ros/otter_subscriber", line 33, in <module>
[otter_subscriber-2]     sys.exit(load_entry_point('otter-ros==1.0.0', 'console_scripts', 'otter_subscriber')())
[otter_subscriber-2]   File "/home/leojt/otter_ws/build/otter_ros/otter_ros/otter_subscriber.py", line 133, in main
[otter_subscriber-2]     otter_sub = OtterSubscriber()
[otter_subscriber-2]   File "/home/leojt/otter_ws/build/otter_ros/otter_ros/otter_subscriber.py", line 47, in __init__
[otter_subscriber-2]     self.stream = self.socket_connect()
[otter_subscriber-2]   File "/home/leojt/otter_ws/build/otter_ros/otter_ros/otter_subscriber.py", line 55, in socket_connect
[otter_subscriber-2]     stream.connect((self.get_parameter('obs_ip_address').value,
[otter_subscriber-2] KeyboardInterrupt
[otter_publisher-1]     otter = OtterPublisher()
[otter_publisher-1]   File "/home/leojt/otter_ws/build/otter_ros/otter_ros/otter_publisher.py", line 54, in __init__
[otter_publisher-1]     self.stream = self.socket_connect()
[otter_publisher-1]   File "/home/leojt/otter_ws/build/otter_ros/otter_ros/otter_publisher.py", line 63, in socket_connect
[otter_publisher-1]     stream.connect((self.get_parameter('obs_ip_address').value,
[otter_publisher-1] KeyboardInterrupt
[otter_tf2_broadcaster-3] Traceback (most recent call last):
[otter_tf2_broadcaster-3]   File "/home/leojt/otter_ws/install/otter_ros/lib/otter_ros/otter_tf2_broadcaster", line 33, in <module>
[otter_tf2_broadcaster-3]     sys.exit(load_entry_point('otter-ros==1.0.0', 'console_scripts', 'otter_tf2_broadcaster')())
[otter_tf2_broadcaster-3]   File "/home/leojt/otter_ws/build/otter_ros/otter_ros/otter_tf2_broadcaster.py", line 156, in main
[otter_tf2_broadcaster-3]     rclpy.shutdown()
[otter_tf2_broadcaster-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 126, in shutdown
[otter_tf2_broadcaster-3]     _shutdown(context=context)
[otter_tf2_broadcaster-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/utilities.py", line 58, in shutdown
[otter_tf2_broadcaster-3]     return context.shutdown()
[otter_tf2_broadcaster-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/context.py", line 102, in shutdown
[otter_tf2_broadcaster-3]     self.__context.shutdown()
[otter_tf2_broadcaster-3] rclpy._rclpy_pybind11.RCLError: failed to shutdown: rcl_shutdown already called on the given context, at ./src/rcl/init.c:241
[ERROR] [otter_publisher-1]: process has died [pid 135728, exit code -2, cmd '/home/leojt/otter_ws/install/otter_ros/lib/otter_ros/otter_publisher --ros-args -r __node:=otter_publisher --params-file /home/leojt/otter_ws/install/otter_ros/share/otter_ros/config/otterUSV.yaml'].
[ERROR] [otter_subscriber-2]: process has died [pid 135730, exit code -2, cmd '/home/leojt/otter_ws/install/otter_ros/lib/otter_ros/otter_subscriber --ros-args -r __node:=otter_subscriber --params-file /home/leojt/otter_ws/install/otter_ros/share/otter_ros/config/otterUSV.yaml'].
[INFO] [static_transform_publisher-6]: process has finished cleanly [pid 135738]
[INFO] [static_transform_publisher-4]: process has finished cleanly [pid 135734]
[INFO] [static_transform_publisher-5]: process has finished cleanly [pid 135736]
[ERROR] [otter_tf2_broadcaster-3]: process has died [pid 135732, exit code 1, cmd '/home/leojt/otter_ws/install/otter_ros/lib/otter_ros/otter_tf2_broadcaster --ros-args -r __node:=otter_tf2_broadcaster'].

**Comment by probablythomas** [comment]
Hi! Thanks for using OtterROS.

What version of ROS2 are you using?

The log suggests an issue with the automatic bag command:
`[ros2-7] ros2 bag record: error: argument -s/--storage: invalid choice: 'mcap' (choose from 'sqlite3', 'my_test_plugin'`
`[ERROR] [ros2-7]: process has died [pid 135740, exit code 2, cmd 'ros2 bag record -a -o otter_bag_2024_08_15T11_11_35 --storage mcap'].`

It looks like you do not have the [MCAP storage plugin ](https://mcap.dev/guides/getting-started/ros-2) installed. We no longer use the default sqlite3 format as the MCAP format can be immediately viewed in Foxglove Studio.

Can you try this command and then run again?
`sudo apt-get install ros-$ROS_DISTRO-rosbag2-storage-mcap`

Let us know if that works!

**Comment by probablythomas** [comment]
Marking this as closed for now, but please let us know if you are still having issues.
